# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - temp-deploy
  paths:
    include:
      - backend

pool:
  name: 'default'
  demands:
    - docker
    - npm

resources:
- repo: self

steps:
- checkout: self
  clean: true

- task: Docker@2
  inputs:
    containerRegistry: 'CerealZ Docker Registry'
    repository: 'hfu_simplicity_cube_backend'
    command: 'buildAndPush'
    Dockerfile: 'backend/Dockerfile'
    buildContext: '**'
    tags: latest

- task: CmdLine@2
  displayName: 'Create dummy file'
  inputs:
    script: 'touch dummy.txt'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

