Class {
	#name : 'Employee',
	#superclass : 'HfuEstimatedReceipt',
	#instVars : [
		'firstName',
		'lastName',
		'receipts',
		'id'
	],
	#category : 'HfuReceiptRecognitionApp'
}

{ #category : 'Not categorized' }
Employee >> firstName [

	^firstName
]

{ #category : 'Not categorized' }
Employee >> id [

	^id
]

{ #category : 'Not categorized' }
Employee >> id: anObject [

	id := anObject
]

{ #category : 'Not categorized' }
Employee >> lastName [

	^lastName
]

{ #category : 'Not categorized' }
Employee >> receipts [

	^receipts
]

{ #category : 'Not categorized' }
Employee >> receipts: anObject [

	receipts := anObject
]
